In [ ]:
!pip install tensorflow

In [3]:
import numpy as np
from keras.models import Sequential
from keras.layers import SimpleRNN,Dense,Embedding
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical

In [6]:
import pandas as pd
df=pd.read_csv("/content/Earth.txt")
df

Empty DataFrame
Columns: [Earth is the third planet from the Sun and the only astronomical object known to harbor life. This is enabled by Earth being a water world,  the only one in the Solar System sustaining liquid surface water. Almost all of Earth's water is contained in its global ocean,  covering  of Earth's crust. The remaining  of Earth's crust is land,  most of which is located in the form of continental landmasses within one hemisphere,  Earth's land hemisphere. Most of Earth's land is somewhat humid and covered by vegetation,  while large sheets of ice at Earth's polar deserts retain more water than Earth's groundwater,  lakes,  rivers and atmospheric water combined. Earth's crust consists of slowly moving tectonic plates,  which interact to produce mountain ranges,  volcanoes,  and earthquakes. Earth has a liquid outer core that generates a magnetosphere capable of deflecting most of the destructive solar winds and cosmic radiation.]
Index: []

In [8]:
#Tokenizing the words
tokenizer=Tokenizer()
tokenizer.fit_on_texts(df)
total_words=len(tokenizer.word_index) + 1
print(total_words)

92


In [9]:
# Creating input sequences and their corresponding next words
input_sequences = []
for df in sentences:
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(tokenized_sentence)):
        n_gram_sequence = tokenized_sentence[:i+1]
        input_sequences.append(n_gram_sequence)
input_sequences

NameError: name 'sentences' is not defined

In [ ]:
# Padding sequences for consistent input size
max_sequence_length = max([len(seq) for seq in input_sequences])
input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_length, padding='pre')
input_sequences

array([[ 0,  0,  0,  1,  2],
       [ 0,  0,  1,  2,  3],
       [ 0,  0,  0,  1,  2],
       [ 0,  0,  1,  2,  4],
       [ 0,  0,  0,  1,  5],
       [ 0,  0,  1,  5,  6],
       [ 0,  0,  0,  7,  8],
       [ 0,  0,  7,  8,  9],
       [ 0,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11]], dtype=int32)

In [ ]:
# Creating input and output data
X, y = input_sequences[:, :-1], input_sequences[:, -1]
y = to_categorical(y, num_classes=total_words)
X,y

(array([[ 0,  0,  0,  1],
        [ 0,  0,  1,  2],
        [ 0,  0,  0,  1],
        [ 0,  0,  1,  2],
        [ 0,  0,  0,  1],
        [ 0,  0,  1,  5],
        [ 0,  0,  0,  7],
        [ 0,  0,  7,  8],
        [ 0,  7,  8,  9],
        [ 7,  8,  9, 10]], dtype=int32),
 array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32))

In [ ]:
# Building a simple RNN model
model = Sequential()
model.add(Embedding(input_dim=total_words, output_dim=50, input_length=max_sequence_length-1))
model.add(SimpleRNN(100, return_sequences=True))
model.add(SimpleRNN(100))
model.add(Dense(total_words, activation='softmax'))

In [ ]:
# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [2]:
# Generating text using the trained model
seed_text = input("Enter the starting word: ")
next_words = int(input("Enter how many words to predict: "))

for _ in range(next_words):
    tokenized_seed = tokenizer.texts_to_sequences([seed_text])[0]
    tokenized_seed = pad_sequences([tokenized_seed], maxlen=max_sequence_length-1, padding='pre')
    predicted_word_index = np.argmax(model.predict(tokenized_seed), axis=-1)
    predicted_word = tokenizer.index_word[predicted_word_index[0]]
    seed_text += " " + predicted_word

print(seed_text)

Enter the starting word: Earth's crust
Enter how many words to predict: 3


NameError: name 'tokenizer' is not defined