In [ ]:
#variable
a=10
print("Iam",a,"years old")

Iam 10 years old


In [ ]:
#arithmetic of two int variables
a=int(input("enter a value"))
b=int(input("enter b value"))
c=a+b
print(c)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print(a//b)


enter a value10
enter b value4
14
6
40
2.5
2
10000
2


In [ ]:
#get salary from the user if the salary is more than 50000 there is 10% of tax.print final salary
n=float(input("enter the salary"))
if(n>=50000):
    i=n*(10/100)
    print("tax:",i)
    print("salary:",n-i)
else:
    print("there is no tax")

enter the salary80000
tax: 8000.0
salary: 72000.0


In [ ]:
#get the salary from the user if the salary is more than or equal to 50000 applay 10% tax reduction
#if the salary is less than 50000 apply 5% tax
#if the salary is more than 70000 aplly 12 % tax
#if the salary exceeds 100000 you are promted to next level
n=float(input("enter salary"))
if n>=50000 and n<70000:
    i=n*(10/100)
    print("salary",n-i)
elif n<50000:
    i=n*(5/100)
    print("salary",n-i)
elif n>=70000 and n<100000:
    i=n*(12/100)
    print("salary",n-i)
else:
    print("you are promoted to next level")

enter salary150000
you are promoted to next level


In [ ]:
#for loop
for i in range(1,16):
      print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [ ]:
a=int(input("enter a value:"))
for i in range(1,16):
      print(a,"x",i,"=",a*i)

enter a value:4
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40
4 x 11 = 44
4 x 12 = 48
4 x 13 = 52
4 x 14 = 56
4 x 15 = 60


In [ ]:
a=int(input("enter a value:"))
i=1
while(i<=15):
     print(a,"x",i,"=",a*i)
     i=i+1

enter a value:6
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60
6 x 11 = 66
6 x 12 = 72
6 x 13 = 78
6 x 14 = 84
6 x 15 = 90


In [ ]:
#create a list
l1=[1,3,4,5,7]
l2=[2,4,5,6,9]
l3=l1[:2]+l2[:3]
print(l3)

[1, 3, 2, 4, 5]


In [ ]:
#list:heterogeneous
l=[1,'jogendra',3.4,'prasad']
for i in l:
    print(i)

1
jogendra
3.4
prasad


In [ ]:
#list:mutable
#listname.append(index,element)
l=[1,'dhoni',1.3,'mahendra']
l.append("hello")
print(l)

[1, 'dhoni', 1.3, 'mahendra', 'hello']


In [ ]:
#listname.extend(listname2)
l1=[2,'jogendra',4.5]
l2=[3,'prasad',3.6]
l1.extend(l2)
print(l1)

[2, 'jogendra', 4.5, 3, 'prasad', 3.6]


In [ ]:
#listname.insert(index,element)
l=[1,'dhoni',1.3,'mahendra']
l.insert(3,"hello")
print(l1)

[1, 'dhoni', 1.3, 'hello', 'mahendra']


In [ ]:
#listname.pop(index)
l=[1,'jogendra',3.4]
l.pop(1)
print(l)

[1, 3.4]


In [ ]:
#listname.remove(element)
l=[1,'jogendra',3.4]
l.remove(3.4)
print(l)

[1, 'jogendra']


In [ ]:
#create a list of 10 integer elements and print its squares
#save these squares in a list
#listname.extend(listname2)
l1=[2,5,8,13,20]
l2=[i*i for i in l1]
print(l2)

[4, 25, 64, 169, 400]


In [ ]:
l1=[2,5,8,13,20]
l2=[i*i for i in l1 if i>10]
print(l2)

[169, 400]


In [ ]:
#LC
#newlist=[(st of is)if(cond)else(st of else)for]
l1=[2,5,8,13,20]
l2=[i*i if i>10 else 'X' for i in l1]
print(l2)

['X', 'X', 'X', 169, 400]


In [ ]:
#take the salary from the user if salary is less than 50000 10% tax otherwise 15% tax
a=[70000,60000,50000,40000,3000]
l1=[i-i*(10/100) if i<50000 else i-i*(15/100) for i in a ]
print(l1)

[59500.0, 51000.0, 42500.0, 36000.0, 2700.0]


In [ ]:
#create an id
dict={'mentor':'jwalitha',35:'nagaraj',34:'gagan',33:'harish'}
print(dict)

{'mentor': 'jwalitha', 35: 'nagaraj', 34: 'gagan', 33: 'harish'}


In [ ]:
dict={'mentor':'jwalitha',35:'nagaraj',34:'gagan',33:'harish'}
print(dict.keys())
print(dict.values())

dict_keys(['mentor', 35, 34, 33])
dict_values(['jwalitha', 'nagaraj', 'gagan', 'harish'])


In [ ]:
dict={'dept':'cse','details':{'section':'d','branch':'cse','rollno':55}}
print('section:',dict['details']['section'])
print('branch:',dict['details']['branch'])
print('rollno:',dict['details']['rollno'])



section: d
branch: cse
rollno: 55


In [ ]:
idl=[34,55,66,77,88]
names=['yashna','mahi','gagan','nagaraj']
new_zip=(zip(idl,names))
for i in new_zip:
      print(i)

(34, 'yashna')
(55, 'mahi')
(66, 'gagan')
(77, 'nagaraj')


In [ ]:
#numpy
import numpy as np
A=np.array([1,2,3,4])  #1d array
print(A.ndim)
print(A.shape)


1
(4,)


In [ ]:
#numpy
import numpy as np
A=np.array([[2,4,5,6],[1,2,3,4],[4,8,12,16],[3,5,7,9]])  #2d array
#elements in each row = column
print(A.ndim)
print(A.shape)
print(A)

2
(4, 4)
[[ 2  4  5  6]
 [ 1  2  3  4]
 [ 4  8 12 16]
 [ 3  5  7  9]]


In [ ]:
#numpy
import numpy as np
A=np.array([[[1,2,3,4],[3,4,5,7],[2,4,8,10]],[[2,3,5,7],[1,3,8,9],[4,8,10,12]]])  #3d array
print(A.ndim)
print(A.shape)
print(A)

3
(2, 3, 4)
[[[ 1  2  3  4]
  [ 3  4  5  7]
  [ 2  4  8 10]]

 [[ 2  3  5  7]
  [ 1  3  8  9]
  [ 4  8 10 12]]]


In [ ]:
A=np.zeros((1,4,3)) #g,r,c
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A=np.ones((1,4,3)) #g,r,c
print(A)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10,2) #start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers divisible by 8
A=np.arange(8,1001,8)
print(A)
print(type(A))

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [ ]:
A=np.linspace(20,30,10) #split in range into n numbers with common differences
print(A)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


In [1]:
#tuples
t1 = ('BMW', 'Tesla', 'Ford', 'Toyota')
print('Total Items:', len(t1))



Total Items: 4


In [2]:
t1 = tuple()
print('t1 =', t1)

# creating a tuple from a list
t2 = tuple([1, 4, 6])
print('t2 =', t2)

# creating a tuple from a string
t1 = tuple('Python')
print('t1 =',t1)

# creating a tuple from a dictionary
t1 = tuple({1: 'one', 2: 'two'})
print('t1 =',t1)

t1 = ()
t2 = (1, 4, 6)
t1 = ('P', 'y', 't', 'h', 'o', 'n')
t1 = (1, 2)


In [5]:
# tuple containing vowels
t1 = ('a', 'e', 'i', 'o', 'u')
t2 = t1.index('i')
print(t2)

2


In [9]:
# tuple containing numbers
t1= (0, 2, 4, 6, 8, 10)
t2=t1.index(4)
print(t2)

2


In [10]:
t1=(1,3,5,6,7)
t2=(2,4,6,8,10)
t3=t1[1:3]+t2[3:]
print(t3)

(3, 5, 8, 10)


In [11]:
t = ('apple','banana','orange')
for i in t:
    print(i)

apple
banana
orange


In [13]:
t1=(12,34,56,78)
t2=(34,76,13,25)
t3=t1+t2
print(t3)

(12, 34, 56, 78, 34, 76, 13, 25)


In [15]:
#sets
#total marks
s1 = {65, 71, 68, 74, 61}
s2 = sum(s1)
print(s2)

# Output: 339

339


In [23]:
s1= {2,4,6,8}
print('Set:',s1)
print('Total Elements:', len(s1))

Set: {8, 2, 4, 6}
Total Elements: 4


In [27]:
#sets using intersection
s1 = {1, 3, 5}
s2 = {1, 2, 3}
print('Intersection using &:', s1 & s2)

Intersection using &: {1, 3}


In [28]:
#sets using union
s1 = {1, 3, 5}
s2 = {1, 2, 3}
print('union using |:', s1 | s2)

union using |: {1, 2, 3, 5}


In [31]:
# sets using difference operation between two sets
s1 = {1, 3, 5}
s2 = {3, 5, 4}
if s1 == s2:
    print('s1 and s2 are equal')
else:
    print('s1 and s2 are not equal')

s1 and s2 are not equal


In [33]:
# updates set1 after the items of set2 is added to set1
s1 = {'a', 'b'}
s2 = {1, 2, 3}
s1.update(s2)
print(s1)

# Output: {'a', 1, 2, 'b', 3}

{1, 2, 3, 'b', 'a'}


In [36]:
# typecasting list to set
s1 = {"a","b","c"}
print(s1)

# Adding element to the set
s1.add("d")
print(s1)


{'c', 'b', 'a'}
{'c', 'd', 'b', 'a'}
