In [ ]:
#tuples
t=[5,3,6,4,9,2]
t.sort()
print(t)

[2, 3, 4, 5, 6, 9]


In [ ]:
#sort elements in a tuple
t1=[5,3,4,6,9,2]
t2=sorted(t1)
print(t2)

[2, 3, 4, 5, 6, 9]


In [ ]:
import numpy as np
A = np.arange(1,13).reshape(4,3)
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np
A=np.linspace(1,15,12).reshape(3,4)
print(A)

[[ 1.          2.27272727  3.54545455  4.81818182]
 [ 6.09090909  7.36363636  8.63636364  9.90909091]
 [11.18181818 12.45454545 13.72727273 15.        ]]


In [ ]:
import numpy as np
A=np.array([11,15,12,8,9,5,6,7]).reshape(2,2,2)
print(A)

[[[11 15]
  [12  8]]

 [[ 9  5]
  [ 6  7]]]


In [ ]:
import numpy as np
A=np.array([45,67,89,12,34,51,90,98])
A.resize(2,2,2) #changes the shape of original array
#reshape - changes needs saving in another variable
print(A)

[[[45 67]
  [89 12]]

 [[34 51]
  [90 98]]]


In [ ]:
A=np.array([34,56,67,78,89])
B=np.array([23,35,56,34,77])
C=A-B
print(C)
print(A+B)
print(A//B)
print(A*B)

[11 21 11 44 12]
[ 57  91 123 112 166]
[1 1 1 2 1]
[ 782 1960 3752 2652 6853]


In [ ]:
A=np.array([34,56,67,78]).reshape(2,2)
B=np.array([23,35,56,34]).reshape(2,2)
C=A-B #matrix substraction
print(C)

[[11 21]
 [11 44]]


In [ ]:
A=np.array([34,56,67,78]).reshape(2,2)
B=np.array([23,35,56,34]).reshape(2,2)
C=A-B #matrix substraction
print(C)
print(A*B)
print(A+B)

[[11 21]
 [11 44]]
[[ 782 1960]
 [3752 2652]]
[[ 57  91]
 [123 112]]


In [ ]:
A= np.array([32.3,35.6,56.2,78.4])
print(A.max())  #min and max values accepts only integer values like float,int
print(A.min())

78.4
32.3


In [ ]:
A= np.array([32,35,78,89,34,56,45,67,23]).reshape(3,3)
print(A)
print("_________________")
print(A.max(axis=0)) #axis 0 -column
print("_________________")
print(A.max(axis=1)) #axis 1- row

[[32 35 78]
 [89 34 56]
 [45 67 23]]
_________________
[89 67 78]
_________________
[78 89 67]


In [ ]:
A = np.array([32,35,78,89,34,56,45,67,23]).reshape(3,3)
print(A)
print("_________________")
print(A.min(axis=0)) #axis 0 -column
print("_________________")
print(A.min(axis=1)) #axis 1- row

[[32 35 78]
 [89 34 56]
 [45 67 23]]
_________________
[32 34 23]
_________________
[32 34 23]


In [ ]:
#after vertically stacking
A = np.array([32,35,78,89,34,56,45,67,23]).reshape(3,3)
B = np.array([45,78,45,56,34,45,56,78,24]).reshape(3,3)
print(A)
print("_________________")
print(B)
print("After vertically stacking the arrays!")
print(np.vstack((A,B)))

[[32 35 78]
 [89 34 56]
 [45 67 23]]
_________________
[[45 78 45]
 [56 34 45]
 [56 78 24]]
After vertically stacking the arrays!
[[32 35 78]
 [89 34 56]
 [45 67 23]
 [45 78 45]
 [56 34 45]
 [56 78 24]]


In [ ]:
A = np.array([32,35,78,89,34,56,45,67,23]).reshape(3,3)
B = np.array([45,78,45,56,34,45,56,78,24]).reshape(3,3)
print(A)
print("_________________")
print(B)
print("After horizontally stacking the arrays!")
print(np.hstack((A,B)))

[[32 35 78]
 [89 34 56]
 [45 67 23]]
_________________
[[45 78 45]
 [56 34 45]
 [56 78 24]]
After horizontally stacking the arrays!
[[32 35 78 45 78 45]
 [89 34 56 56 34 45]
 [45 67 23 56 78 24]]


In [ ]:
#after dstack
A = np.array([32,35,78,89,34,56,45,67,23]).reshape(3,3)
B = np.array([23, 45, 67, 78, 56,67,45,89,45]).reshape(3,3)
print(A)
print(B)
print("After dstack")
print(np.dstack(A))
print(np.dstack(B)) #no of rows -->no of groups
#no of col in every group --> no of rows in every group

[[32 35 78]
 [89 34 56]
 [45 67 23]]
[[23 45 67]
 [78 56 67]
 [45 89 45]]
After dstack
[[[32 89 45]
  [35 34 67]
  [78 56 23]]]
[[[23 78 45]
  [45 56 89]
  [67 67 45]]]


In [ ]:
#after splitting
A=np.arange(18).reshape(6,3)
print(A)
print("After Splitting")
np.vsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#after splitting
A=np.arange(18).reshape(6,3)
print(A)
print("After Splitting")
np.vsplit(A,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#after splitting
A=np.arange(18).reshape(6,3)
print(A)
print("After Splitting")
np.hsplit(A,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After Splitting


[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13],
        [15, 16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
#after splitting
A=np.arange(12).reshape(4,3)
print(A)
print("After Splitting")
np.hsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After Splitting


[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [ ]:
#after splitting
A=np.arange(24,48).reshape(6,4)
print(A)
print(A.argmax())


[[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
23


In [ ]:
#after splitting
A=np.arange(24,48).reshape(6,4)
print(A)
print(A.argmax())

[[24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
23


In [ ]:
#after splitting
A=np.array([24,48,45,67,45,65,78,34,56,89,23,45,56,89,19,34,56,78]).reshape(3,6)
print(A)
print(A.argmax())

[[24 48 45 67 45 65]
 [78 34 56 89 23 45]
 [56 89 19 34 56 78]]
9


In [ ]:
#after splitting
A=np.array([24,48,45,67,45,65,78,34,56,89,23,45,56,89,19,34,56,78]).reshape(3,6)
print(A)
print(A.argmin())

[[24 48 45 67 45 65]
 [78 34 56 89 23 45]
 [56 89 19 34 56 78]]
14


In [ ]:
#after splitting
A=np.array([24,48,45,67,45,65,78,34,56,89,23,45,56,89,19,34,56,78]).reshape(3,6)
print(A)
print(A.argmax(axis=0))

[[24 48 45 67 45 65]
 [78 34 56 89 23 45]
 [56 89 19 34 56 78]]
[1 2 1 1 2 2]


In [ ]:
#after splitting
A=np.array([24,48,45,67,45,65,78,34,56,89,23,45,56,89,19,34,56,78]).reshape(3,6)
print(A)
print(A.argmin(axis=0))

[[24 48 45 67 45 65]
 [78 34 56 89 23 45]
 [56 89 19 34 56 78]]
[0 1 2 2 1 1]


In [ ]:
#after splitting
A=np.array([24,48,45,67,45,65,78,34,56,89,23,45,56,89,19,34,56,78]).reshape(3,6)
print(A)
print(A.argmax(axis=1))

[[24 48 45 67 45 65]
 [78 34 56 89 23 45]
 [56 89 19 34 56 78]]
[3 3 1]


In [ ]:
#after splitting
A=np.array([24,48,45,67,45,65,78,34,56,89,23,45,56,89,19,34,56,78]).reshape(3,6)
print(A)
print(A.argmin(axis=1))

[[24 48 45 67 45 65]
 [78 34 56 89 23 45]
 [56 89 19 34 56 78]]
[0 4 2]


In [ ]:
#mean,median,std,var
A=np.array([12,34,25,66,71,88])
print("mean:",np.mean(A))
print("median:",np.median(A))
print("variance:",np.var(A))
print("standard dev:",np.std(A))






mean: 49.333333333333336
median: 50.0
variance: 743.888888888889
standard dev: 27.274326552435515


In [ ]:
A=np.pi
print(A)   #radians

3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
np.deg2rad(A)

array([0.01370778, 0.01827705, 0.02741557, 0.05483114])

In [ ]:
A = np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(A)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
B=np.array([30,45,60,90,120,180,360])
C=np.deg2rad(B)
print(C)

[0.52359878 0.78539816 1.04719755 1.57079633 2.0943951  3.14159265
 6.28318531]


In [ ]:
np.sin(C)

array([ 5.00000000e-01,  7.07106781e-01,  8.66025404e-01,  1.00000000e+00,
        8.66025404e-01,  1.22464680e-16, -2.44929360e-16])

In [ ]:
np.cos(C)

array([ 8.66025404e-01,  7.07106781e-01,  5.00000000e-01,  6.12323400e-17,
       -5.00000000e-01, -1.00000000e+00,  1.00000000e+00])

In [ ]:
np.tan(C)

array([ 5.77350269e-01,  1.00000000e+00,  1.73205081e+00,  1.63312394e+16,
       -1.73205081e+00, -1.22464680e-16, -2.44929360e-16])

In [ ]:
np.arcsin(1)  #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1)  #cos^-1

0.0

In [ ]:
np.arctan(1) #tan^-1

0.7853981633974483

In [ ]:
a=12
b=5
print(np.hypot(a,b))

13.0


In [ ]:
#searching an array
A=np.array([34,45,67,89,23])
print(np.where(A==45))

(array([1]),)


In [ ]:
A=np.array([90,45,67,89,12])
print(np.where(A%2==0)) #even

(array([0, 4]),)


In [ ]:
A=np.array([90,45,67,89,12])
print(np.where(A>25)) #greater than 25

(array([0, 1, 2, 3]),)


In [14]:
import numpy as np
A=np.array([90,45,21,34,90,13])
B=np.sort(A)
print(np.searchsorted(A,45))
print(B)
#13,21,34,45,90,90

6
[13 21 34 45 90 90]


In [20]:
import numpy as np
A=np.array([34,56,78,89])
B=np.array([23,56,79,25])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.divide(A,B))
print(np.multiply(A,B))
print(np.mod(A,B))
print(np.divmod(A,B))

[ 57 112 157 114]
[11  0 -1 64]
[1.47826087 1.         0.98734177 3.56      ]
[ 782 3136 6162 2225]
[11  0 78 14]
(array([1, 1, 0, 3]), array([11,  0, 78, 14]))


In [23]:
A=np.array([18,12,32,24,16,40])
print(np.sort(A))
print(np.diff(A))

[12 16 18 24 32 40]
[-6 20 -8 -8 24]


In [24]:
A=np.array([6,12,56,78,23])
B=np.array([34,56,12,35,37])
print(np.union1d(A,B))

[ 6 12 23 34 35 37 56 78]


In [26]:
A=np.array([6,12,56,78,23])
B=np.array([34,56,12,35,37])
print(np.setdiff1d(A,B))

[ 6 23 78]


In [27]:
A=np.array([6,12,56,78,23])
B=np.array([34,56,12,35,37])
print(np.intersect1d(A,B))

[12 56]


In [32]:
#rounding
A1=np.around([3.16378,3.66689])
A2=np.ceil([-3.16378,3.66689])
A3=np.floor([-3.16378,3.66689])
A4=np.fix([-3.16378,3.66689])
A5=np.trunc([3.16378,-3.66689])
print(A1)
print(A2)
print(A3)
print(A4)
print(A5)

[3. 4.]
[-3.  4.]
[-4.  3.]
[-3.  3.]
[ 3. -3.]


In [38]:
A=np.array([4,8,9,10,14])
print(np.cumsum(A))
print(np.cumprod(A))

[ 4 12 21 31 45]
[    4    32   288  2880 40320]


In [36]:
print(np.lcm(45,34))
print(np.gcd(6,24))

1530
6


In [40]:
Ar=np.array([45,36,78])
print(np.lcm.reduce(Ar))
print(np.gcd.reduce(Ar))

2340
3


In [43]:
A=np.array([[1,2],[3,4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [47]:
from numpy import random as rd
A=rd.rand()
A=rd.rand(10) #limit 0 to 0.99
print(A)

[0.10216953 0.3879004  0.17738319 0.08290191 0.89175509 0.68592116
 0.59055    0.90148379 0.77732686 0.89091365]


In [50]:
A=rd.randint(4)
B=rd.randint(5)
print(A) #limit 0 to 4
print(B) #limit 0 to 5

1
2


In [52]:
A=rd.randint(4,size=6)
print(A)

[0 3 1 0 2 2]


In [58]:
A=np.array([1,3,5])
B=np.array([2,4,6])
print(np.inner(A,B))  #1x4 + 2x5 + 3x6
print(np.outer(A,B))
print(np.cross(A,B))


44
[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]
[-2  4 -2]
